---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service
  namespace: klokkinn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
      annotations: {}
    spec:
      containers:
      - name: time-service
        image: ghcr.io/klokkinn/time-service:v0.0.8
        env:
        - name: DISCOVERY_URL
          value: https://deifyed.eu.auth0.com/.well-known/openid-configuration
