---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service
  namespace: klokkinn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
    spec:
      containers:
      - name: time-service
        image: docker.pkg.github.com/klokkinn/time-service/time-service:0.0.1
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: time-service
              key: dsn
        - name: DISCOVERY_URL
          value: https://auth.klokkinn.no/wellknown

