/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/klokkinn/time-service/pkg/core"

	"github.com/klokkinn/time-service/pkg/core/router"
)

func main() {
	log.Printf("Server started")

	cfg := core.LoadConfig()

	if err := cfg.Validate(); err != nil {
		log.Fatal(err)
	}

	server := router.New(cfg)

	log.Fatal(server.Run(":3000"))
}
