/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/klokkinn/time-service/pkg/core/router"
)

func main() {
	log.Printf("Server started")

	server := router.New()

	log.Fatal(server.Run(":3000"))
}
