/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteEntry - Delete an existing time Entry
func DeleteEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetEntry - Get detailed information about a single time Entry
func GetEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateEntry - Edit an existing time Entry
func UpdateEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
