/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/klokkinn/time-service/pkg/core"

	"github.com/gin-gonic/gin"
)

// AddEntry - Create a new time Entry
func AddEntry(_ core.StorageClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{})
	}
}

// GetAllEntries - Returns a list of time entries
func GetAllEntries(_ core.StorageClient) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{})
	}
}
