/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AddEntry - Create a new time Entry
func AddEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAllEntries - Returns a list of time entries
func GetAllEntries(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
