/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router

import (
	"net/http"

	"github.com/klokkinn/time-service/pkg/core/handlers"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// New returns a new router.
func New() *gin.Engine {
	router := gin.Default()

	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/api/time/",
		Index,
	},

	{
		"AddEntry",
		http.MethodPost,
		"/api/time/entries",
		handlers.AddEntry,
	},

	{
		"GetAllEntries",
		http.MethodGet,
		"/api/time/entries",
		handlers.GetAllEntries,
	},

	{
		"DeleteEntry",
		http.MethodDelete,
		"/api/time/entries/:id",
		handlers.DeleteEntry,
	},

	{
		"GetEntry",
		http.MethodGet,
		"/api/time/entries/:id",
		handlers.GetEntry,
	},

	{
		"UpdateEntry",
		http.MethodPatch,
		"/api/time/entries/:id",
		handlers.UpdateEntry,
	},
}
