/*
 * Time Service
 *
 * An API for registrating time
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Entry - The main object which describes a timeframe. The time here uses Unix Nano to define time
type Entry struct {
	Id string `json:"id"`

	Start string `json:"start"`

	End string `json:"end,omitempty"`
}
